#!/usr/bin/env Rscript
# Title: Schisto_sex_RD.R
# Version: 1.0
# Author: Frédéric CHEVALIER <fcheval@txbiomedgenetics.org>
# Created in: 2014-04-20
# Modified in: 2020-11-12



#==========#
# Comments #
#==========#

aim <- "Compute ratio between the mean read depth (RD) of the Z-linked region and the mean RD from the remaining Z chromosome. If the ratio is around 1, the individual is a male, if the ratio is around 0.5, the individual is a female."



#==========#
# Versions #
#==========#

# v1.0 - 2020-11-12: script updated to work with latest Sm genome (WBPS14) / ratio computation improved
# v0.1 - 2015-02-07: argument parsing added / default location replaced with current position
# v0.0 - 2014-04-20: creation


#===================#
# Packages required #
#===================#

suppressMessages({
    library(argparser)
    library(magrittr)
    library(tools)
})



#===========#
# Variables #
#===========#

# Options
myparser <- arg_parser(aim)
myparser <- add_argument(myparser, "--file", help="read depth file generated by bedtools genomecov. Must contain 3 columns: chromosome, position, read depth.", default = NULL)

argv <- parse_args(myparser)

if (is.null(argv$file)) { stop("file missing") }



#=================#
# Data processing #
#=================#

mydata <- read.delim(argv$file, header = FALSE)

# Object contaning the input file name
filename <- file_path_sans_ext(argv$file)

# Z chromosome only
mydata_chrZ <- mydata[mydata[,1] == "SM_V7_ZW", ]

# Smoothing data
mydata_chrZ[, 3] <- runmed(mydata_chrZ[, 3], 101)

# Reducing data by removing low covered regions
mydata_chrZ <- mydata_chrZ[mydata_chrZ[,3] > 5, ]

# Z-linked region
Z_linked_region <- mydata_chrZ[,2] >= 11e6 & mydata_chrZ[,2] <= 44e6

# Z-linged mean read depth
Z_linked_RD <- mydata_chrZ[Z_linked_region, 3] %>% mean() %>% round(., 2)

# Z chromosome mean RD (other than Z-linked)
Z_other_RD <- mydata_chrZ[! Z_linked_region, 3] %>% mean() %>% round(., 2)

# Ratio
ratio <- Z_linked_RD / Z_other_RD

# Sexing
if (is.na(ratio)) {
    sex <- "NA"
} else {
    if (ratio < 0.8) {
        sex <- "female"
    } else {
        sex <- "male"
    }
}

# Report
report <- c(paste0(Z_linked_RD, "/", Z_other_RD), ratio, sex)
write(report, paste0(filename, ".sex"))

q(status=0)
